parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     symfony_test
    database_user:     root
    database_password:

    mailer_transport:  gmail
    mailer_host:       smtp.gmail.com
    mailer_user:       gdeveloperaccount@gmail.com
    mailer_password:   mqmd3vpass

    locale:            es
    secret:            TestPasswordForHackersBeingTested
